services:
  swagger-ui:
   image: swaggerapi/swagger-ui
   container_name: contenedor-swagger
   ports:
      - "8080:8080"
   volumes:
      - ./docs:/usr/share/nginx/html/docs
   environment:
      #     API_URL: docs/{nombre del fichero yaml que quieren abrir}
      #     Por ejemplo:
      #     API_URL: docs/openapi.yaml
      # --------------- Descomentar el archivo de documentación ----------------
      # --------------- para abrir por defecto ----------------

      API_URL: docs/api_reference_microframework/openapi.yaml
      # API_URL: docs/claro/claro_drive/openapi.yaml
      # API_URL: docs/claro/claro_video/openapi.yaml
